# Configuration for Continuous Integration (CI) of smart contract monitoring ecosystem

contracts:
  # - name: "ProductOrder"
  #   constructorParamSpecs:
  #     - name: "_price"
  #       type: "uint256"
  #       sourceType: "static"
  #       value: 1
  #   models:
  #     - name: "ProductOrder"
  #       id: "1822680"
  #       functions: []
  #       hasResponseRelation: true
  #   tests:
  #     - "ProductOrderExploit"

  # - name: "ProductOrder"
  #   constructorParamSpecs:
  #     - name: "_price"
  #       type: "uint256"
  #       sourceType: "static"
  #       value: 1
  #   models:
  #     - name: "ProductOrder"
  #       id: "1822680"
  #       functions: []
  #       hasResponseRelation: true
  #   tests:
  #     - "ProductOrderExploit"

tests:
  - name: "HelloWorldExploit"
    description: "Exploits for time lock-based property of HelloWorld contract"
    directory: "/exploits/"
    files:
      - "HelloWorldExploit.js"
    environment: "anvil"

  - name: "PrizeDistributionExploit"
    description: "Exploits for time-based vulnerability of PrizeDistribution contract which is enabled by a poor logic in the contract implementation."
    directory: "/exploits/"
    files:
      - "PrizeDistributionExploit.js"
    environment: "anvil"

  - name: "MultiStageAuctionExploit"
    description: "Exploits for a temporal property of ..."
    directory: "/exploits"
    files:
      - "MultiStageAuctionExploit.js"
    environment: "anvil"

  - name: "ProductOrderExploit"
    description: "No description yet..."
    directory: "/exploits"
    files:
      - "ProductOrderExploit.js"
    environment: "anvil"

  - name: "ProductOrderExploit2"
    description: "No description yet..."
    directory: "/exploits"
    files:
      - "ProductOrderExploit2.js"
    environment: "anvil"

  - name: "EscrowExploit"
    description: "No description yet..."
    directory: "/exploits"
    files:
      - "EscrowExploit.js"
    environment: "anvil"

  - name: "GovernanceExploit"
    description: "No description yet..."
    directory: "/exploits"
    files:
      - "GovernanceExploit.js"
    environment: "anvil"

environments:
  - name: "anvil"
    version: "0.2.0"
