# Configuration for Continuous Integration (CI) of smart contract monitoring ecosystem

contracts:
  # - name: "ProductOrder"
  #   models:
  #     - name: "Model1"
  #       id: "1701030" # The id of the model in DCRGraphs.net website
  #       functions:
  #         functionIdentifier1:
  #           paramIdentifier1:
  #             EVMType: "..."
  #             DCRType: "..."
  #             DCRNodeID: "..."
  #           roleSetter: true
  #           roleVariableIdentifier: "owner"

  #         functionIdentifier2:
  #           paramIdentifier2:
  #             EVMType: "..."
  #             DCRType: "..."
  #             DCRNodeID: "..."
  #           roleSetter: true
  #           roleVariableIdentifier: "owner"
  #     - name: "Model2"
  #       id: "1701159"
  #       functions:
  #         setGreet:
  #           EVMType: "string"
  #           DCRType: "integer"
  #           DCRNodeID: "setGreet"
  #   tests: # if there are tests specified for the specific monitor, it will run them alongside the monitor automatically. Otherwise, only thing that will run is the monitor
  #     - "ProductOrder"
  #     - "Contract1TemporalExploits2"

  - name: "HelloWorld"
    models:
      - name: "HelloWorld Model"
        id: "1702173" # The id of the model in DCRGraphs.net website
        # Plugin conventions if any, to execute (in order)
        # conventions:
        #  - name: ""
        functions:
          setGreet:
            EVMType: "string"
            DCRType: "integer"
            DCRNodeID: "setGreet"
    tests:
      - "HelloWorldExploit"

tests:
  - name: "HelloWorldExploit"
    description: "Exploits for temporal properties of HelloWorld Contract"
    directory: "/tests/exploits/"
    files:
      - "HelloWorldExploit.js"
    environment: "anvil"

environments:
  - name: "anvil"
    version: "0.2.0"
