# Configuration for Continuous Integration (CI) of smart contract monitoring ecosystem

tests:
  - name: "Exploit monitoring integration tests"
    directory: "/tests/exploits/"
    files:
      - "exp1.js"
    environment: "anvil"

environments:
  - name: "anvil"
    version: "0.2.0"
